name: C++ with CMake CI

on: [push, pull_request]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run check.sh
      working-directory: shm
      run: |
        cd shm
        chmod +x check.sh
        ./check.sh

# In case of conflict do not remove above jobs. Just add your jobs below and remove this comment :)
