name: C++ with CMake CI

on: [push, pull_request]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run check.sh
      run: |
        pwd
        ls
        chmod +x shm/check.sh
        shm/check.sh

# In case of conflict do not remove above jobs. Just add your jobs below and remove this comment :)
